import { Chapter, Dialog, Metadata, Choice, Character, Data } from "./spec";

import win from "../assets/audio/win.mp3";
import loose from "../assets/audio/loose.mp3";

import RozprawaSądowaTło from "../assets/images/rozprawa_sądowa.jpg";
import RozprawaSądowaMuzyka from "../assets/audio/rozprawa_sądowa.mp3";

import Adwokat from "../assets/images/adwokat.png";
import Baronowa from "../assets/images/baronowa.png";
import Dziecko from "../assets/images/dziecko.png";
import Maruszewicz from "../assets/images/maruszewicz.png";
import Rzecki from "../assets/images/rzecki.png";
import Sędzia from "../assets/images/sędzia.png";
import Służąca from "../assets/images/służąca.png";
import Stawska from "../assets/images/stawska.png";
import Wokulski from "../assets/images/wokulski.png";

export const metadata: Metadata = {
  win,
  loose,
};

export const chapters: Chapter[] = [
  {
    id: 1,
    name: "Rozprawa Sądowa",
    slug: "rozprawa-sadowa",
    audio: RozprawaSądowaMuzyka,
    background: RozprawaSądowaTło,
  },
];

export const dialogs: Dialog[] = [
  {
    id: 1,
    chapterId: 1,
    characterId: 7,
    type: "default",
    text: "Sędzia przez parę minut coś pisał, a skończywszy zawiadomił obecnych, że teraz toczyć się będzie sprawa",
  },
  {
    id: 2,
    chapterId: 1,
    characterId: 7,
    type: "default",
    text: "Sędzia zawezwał obie strony oraz świadków na środek sali.",
  },
  {
    id: 3,
    chapterId: 1,
    characterId: 2,
    text: "Rzecki siada w ławce, przysłuchując się rozmowie dwóch kobiet. Jedna z kumoszek tłumaczyła drugiej...",
    type: "default",
  },
  {
    id: 4,
    chapterId: 1,
    characterId: 10,
    text: "To widzi pani: ta ładna pani ukradła tamtej pani lalkę...",
    type: "default",
  },
  {
    id: 5,
    chapterId: 1,
    characterId: 11,
    text: "Także miała się na co łakomić!...",
    type: "default",
  },
  {
    id: 6,
    chapterId: 1,
    characterId: 10,
    text: "Ha, trudno. Nie każdy może kraść magle...",
    type: "default",
  },
  {
    id: 7,
    chapterId: 1,
    characterId: 12,
    text: "To pani ukradłaś magle. Nie ten złodziej, co zabiera swoją własność, ale ten, co da piętnaście rubli zadatku i myśli, że już kupił...",
    type: "default",
  },
  {
    id: 8,
    chapterId: 1,
    characterId: 13,
    text: "Helunia wbiega na salę i chwyta matkę za rękę",
    type: "default",
  },
  {
    id: 9,
    chapterId: 1,
    characterId: 13,
    text: "Mamo, czego ten pan kazał mamie tu przyjść?… Ja coś powiem do uszka: pewnie mama była niegrzeczna i teraz bęǳie stać w kącie...",
    type: "default",
  },
  {
    id: 10,
    chapterId: 1,
    characterId: 10,
    text: "To wyuczone!...",
    type: "default",
  },
  {
    id: 11,
    chapterId: 1,
    characterId: 12,
    text: "Żebyś pani tak zdrowa była!",
    type: "default",
  },
  {
    id: 12,
    chapterId: 1,
    characterId: 10,
    text: "Pan bęǳiesz zdrów za moją krzywdę...",
    type: "default",
  },
  {
    id: 13,
    chapterId: 1,
    characterId: 12,
    text: "A pani skonasz na konwulsje i będą cię w piekle maglować na moich maglach",
    type: "default",
  },
  {
    id: 14,
    chapterId: 1,
    characterId: 2,
    text: "Rzecki wtrąca się do kłótni stając w obronie Stawskiej",
    type: "default",
  },
  {
    id: 15,
    chapterId: 1,
    characterId: 7,
    text: "Cisza na sali! Co pani Krzeszowska mówi o sprawie?",
    type: "default",
  },
  {
    id: 16,
    chapterId: 1,
    characterId: 4,
    text: "Wysłuchaj mnie, panie sęǳio! Po zmarłym ǳiecku została mi, jako najdroższa pamiątka, lalka, która barǳo podobała się tej oto pani i jej córce",
    type: "default",
  },
  {
    id: 17,
    chapterId: 1,
    characterId: 7,
    text: "Oskarżona była u pani?",
    type: "default",
  },
  {
    id: 18,
    chapterId: 1,
    characterId: 4,
    text: "Tak, wynajmowałam ją do szycia...",
    type: "default",
  },
  {
    id: 19,
    chapterId: 1,
    characterId: 14,
    text: "Alem jej nic nie zapłaciła!",
    type: "default",
  },
  {
    id: 20,
    chapterId: 1,
    characterId: 7,
    text: "Ciszej! Proszę kontynuować",
    type: "default",
  },
  {
    id: 21,
    chapterId: 1,
    characterId: 4,
    text: "W dniu, w którym tę panią oddaliłam od siebie, zginęła mi lalka. Myślałam, że umrę z żalu, i zaraz na nią powzięłam podejrzenie...",
    type: "default",
  },
  {
    id: 22,
    chapterId: 1,
    characterId: 4,
    text: "Miałam dobre przeczucie, gdyż w kilka dni później przyjaciel mój, pan Maruszewicz, zobaczył z okna, że ta pani (która mieszka vis a vis niego) ma u siebie moją lalkę i dla niepoznaki przebiera ją w inną suknię.",
    type: "default",
  },
  {
    id: 23,
    chapterId: 1,
    characterId: 4,
    text: "Wtedy poszłam do jego mieszkania z moim doradcą prawnym i zobaczyłam przez lornetkę, że moja lalka jest rzeczywiście u tej pani. Na drugi ǳień więc udałam się do niej, zabrałam lalkę, którą tu wiǳę na stole, i podałam skargę.",
    type: "default",
  },
  {
    id: 24,
    chapterId: 1,
    characterId: 7,
    text: "A pan Maruszewicz jest pewny, że to ta sama lalka, która była u pani Krzeszowskiej?",
    type: "default",
  },
  {
    id: 25,
    chapterId: 1,
    characterId: 6,
    text: "Marusiewicz wstał i powiedział:",
    type: "default",
  },
  {
    id: 26,
    chapterId: 1,
    characterId: 7,
    text: "Zatem świadków jest dużo. Jeśli lalka rzeczywiście wygląda podobnie - w co jestem skłonny uwierzyć - to muszę przyznać winę pannie Helenie Stawskiej.",
    type: "default",
  },
  {
    id: 27,
    chapterId: 1,
    characterId: 7,
    text: "Tak dlaczegóż pan Maruszewicz powiedział to pani Krzeszowskiej?",
    type: "default",
  },
  {
    id: 28,
    chapterId: 1,
    characterId: 6,
    text: "Właściwie... ja nie w tym znaczeniu...",
    type: "default",
  },
  {
    id: 29,
    chapterId: 1,
    characterId: 4,
    text: "Nie kłam pan! Przybiegłeś do mnie, śmiejąc się, powiedziałeś, że Stawka ukradła lalkę i że to do niej podobne...",
    type: "default",
  },
  {
    id: 30,
    chapterId: 1,
    characterId: 1,
    text: "Podlec",
    type: "default",
  },
  {
    id: 31,
    chapterId: 1,
    characterId: 7,
    text: "U was była ta lalka?",
    type: "default",
  },
  {
    id: 32,
    chapterId: 1,
    characterId: 9,
    text: "Stawska nieśmiało powiedziała:",
    type: "default",
  },
  {
    id: 33,
    chapterId: 1,
    characterId: 7,
    text: "Sędzia wyciągnął do niej lalkę, ale służąca milczała mrugając oczyma i załamując ręce.",
    type: "default",
  },
  {
    id: 34,
    chapterId: 1,
    characterId: 13,
    text: "Ach, to Mimi!...",
    type: "default",
  },
  {
    id: 35,
    chapterId: 1,
    characterId: 4,
    text: "O, panie sędzio! Córka świadczy przeciw matce...",
    type: "default",
  },
  {
    id: 36,
    chapterId: 1,
    characterId: 7,
    text: "Znasz tę lalkę?",
    type: "default",
  },
  {
    id: 37,
    chapterId: 1,
    characterId: 13,
    text: "O, znam!... Zupełnie taka sama była u pani tam w pokoiku...",
    type: "default",
  },
  {
    id: 38,
    chapterId: 1,
    characterId: 7,
    text: "Czy to jest ta sama?",
    type: "default",
  },
  {
    id: 39,
    chapterId: 1,
    characterId: 13,
    text: "O, nie, nie ta... Tamta miała",
    type: "default",
  },
  {
    id: 40,
    chapterId: 1,
    characterId: 4,
    text: "Kłamstwo! Moja lalka nie miała czerwonej sukienki. Panie sędzio, czy skoro kłamią w takich drobnostkach, czy można im ufać w ogóle?",
    type: "default",
  },
  {
    id: 41,
    chapterId: 1,
    characterId: 7,
    text: "Co pani Stawska powie?...",
    type: "default",
  },
  {
    id: 42,
    chapterId: 1,
    characterId: 9,
    text: "Lalkę tę kupiłam w sklepie pana Wokulskiego...",
    type: "default",
  },
  {
    id: 43,
    chapterId: 1,
    characterId: 4,
    text: "A ile pani dała za nią?...",
    type: "default",
  },
  {
    id: 44,
    chapterId: 1,
    characterId: 9,
    text: "Stawska odpowiedziała:",
    type: "default",
  },
  {
    id: 45,
    chapterId: 1,
    characterId: 4,
    text: "Tyle, co zapłaciłam ja! Czy to nie jest jednoznacznym dowodem na to, że to jest ta sama lalka, która została u mnie przez nią skradziona?",
    type: "default",
  },
  {
    id: 1000,
    chapterId: 1,
    characterId: null,
    text: "Brawo Graczu! Wykazałeś się znajomością lektury. Dzięki Tobie uniewinniono Helenę Stawską. Składamy szczere gratulacje od całej ekipy twórców",
    type: "success",
  },
  {
    id: 1001,
    chapterId: 1,
    characterId: null,
    text: "Mam wrażenie, że nie przeczytałeś lektury. Spróbuj ponownie",
    type: "failure",
  },
  {
    id: 1002,
    chapterId: 1,
    characterId: null,
    text: "Ignacy Rzecki został wyproszony z sali rozpraw przez kłótnię, doprowadzając do przegranej Stawskiej. Spróbuj ponownie",
    type: "failure",
  },
  {
    id: 1003,
    chapterId: 1,
    characterId: null,
    text: "Sędzia uwierzył w kłamstwo Maruszewicza, co doprowadza do przegrane Heleny Stawskiej. Spróbuj ponownie",
    type: "failure",
  },
  {
    id: 1004,
    chapterId: 1,
    characterId: null,
    text: "Pani Stawska nie mogła wytrzymać stresu, który w niej powodowała rozprawa. Liczyła, że dzięki pomocy Ignacego Rzeckiego i Stanisława Wokulskiego uda jej się dojść do wystarczająco pokojowego rozwiązania konfliktu. Niestety baronowa Krzeszowska dobijała się o największą możliwą karę dla Heleny. Niewiele pomogły słowa Rzeckiego i Wokulskiego, kiedy sama przyznała się do rzekomej winy. Stawska przegrała proces",
    type: "failure",
  },
  {
    id: 1005,
    chapterId: 1,
    characterId: null,
    text: "Słowa strony Stawskiej były odbierane z o wiele mniejszym zaufaniem. Ostatecznie baronowej Krzeszowskiej udało się przekonać sędzię o swojej racji. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1006,
    chapterId: 1,
    characterId: null,
    text: "Baronowa Krzeszowska przeciągnęła sędzie na swoją stronę. Skłamała później, że lalkę kupiła w sklepie Stanisława Wokulskiego. Postanowiono, iż baronowa mogła kupić Lalkę w momencie, kiedy w pobliżu nie było ani Rzeckiego, ani Wokulskiego, a więc ich zaprzeczenia słów Krzeszowskiej zostały odebrane jako kłamstwa w celu wybielenia Stawskiej. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1007,
    chapterId: 1,
    characterId: null,
    text: "Pani Stawska została uznana za kłamczynię. Baronowa Krzeszowska więc bez dużego wysiłku przekonała sędzię i ławę przysiężnych, iż jej wersja jest prawdziwa. Nikt nie zwątpił nawet w jej kłamstwo - że rzekomo kupiła lalkę u Wokulskiego. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1008,
    chapterId: 1,
    characterId: null,
    text: "Ignacy Rzecki zaczął się gubić w myślach, więc nie mógł zaoferować pożytecznej pomocy dla Heleny Stawskiej. Sama Pani Stawska nie dała rady obronić.",
    type: "failure",
  },
  {
    id: 1009,
    chapterId: 1,
    characterId: null,
    text: "Kłamstwo baronowej Krzeszowskiej wydało się wiarygodnym zarówno sędziemu, jak i ławie przysiężnych. Dodatkowo zostało potwierdzone przez jej służącą. Zaprzeczenia Stanisława Wokulskiego zostały potraktowane jako kłamstwo w celu wybielenia Heleny Stawskiej. Ostatecznie Krzeszowska zwyciężyła. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1010,
    chapterId: 1,
    characterId: null,
    text: "Stanisław Wokulski postanowił nie robić przykrości Heluni niszcząc jej zabawkę na jej oczach. Niestety przez to sędzia nie mógł zobaczyć napisu w środku lalki, który posłużyłby jednoznacznym dowodem. Nie udało się znaleźć wystarczająco dobrych argumentów i baronowej Krzeszowskiej udało się przekonać sędzię, iż ma rację. Stawska przegrała proces.",
    type: "failure",
  },
];

export const choices: Choice[] = [
  {
    id: 1,
    next: 2,
    dialogId: 1,
    text: "Krzeszowskiej przeciw Stawskiej o kradzież lalki",
  },
  {
    id: 2,
    next: 1001,
    dialogId: 1,
    text: "Wokulski przeciw Stawskiej o kradzież lalki",
  },
  {
    id: 3,
    next: 3,
    dialogId: 2,
    text: "Dalej",
  },
  {
    id: 4,
    next: 4,
    dialogId: 3,
    text: "Dalej",
  },
  {
    id: 5,
    next: 5,
    dialogId: 4,
    text: "Dalej",
  },
  {
    id: 6,
    next: 6,
    dialogId: 5,
    text: "Dalej",
  },
  {
    id: 7,
    next: 7,
    dialogId: 6,
    text: "Dalej",
  },
  {
    id: 8,
    next: 8,
    dialogId: 7,
    text: "Dalej",
  },
  {
    id: 9,
    next: 9,
    dialogId: 8,
    text: "Dalej",
  },
  {
    id: 10,
    next: 10,
    dialogId: 9,
    text: "Dalej",
  },
  {
    id: 11,
    next: 11,
    dialogId: 10,
    text: "Dalej",
  },
  {
    id: 12,
    next: 12,
    dialogId: 11,
    text: "Dalej",
  },
  {
    id: 13,
    next: 13,
    dialogId: 12,
    text: "Dalej",
  },
  {
    id: 14,
    next: 14,
    dialogId: 13,
    text: "Dalej",
  },
  {
    id: 15,
    next: 1002,
    dialogId: 14,
    text: "Dalej",
  },
  {
    id: 16,
    next: 16,
    dialogId: 15,
    text: "Dalej",
  },
  {
    id: 17,
    next: 17,
    dialogId: 16,
    text: "Dalej",
  },
  {
    id: 18,
    next: 18,
    dialogId: 17,
    text: "Dalej",
  },
  {
    id: 19,
    next: 19,
    dialogId: 18,
    text: "Dalej",
  },
  {
    id: 20,
    next: 20,
    dialogId: 19,
    text: "Dalej",
  },
  {
    id: 21,
    next: 21,
    dialogId: 20,
    text: "Dalej",
  },
  {
    id: 22,
    next: 22,
    dialogId: 21,
    text: "Dalej",
  },
  {
    id: 23,
    next: 23,
    dialogId: 22,
    text: "Dalej",
  },
  {
    id: 24,
    next: 24,
    dialogId: 23,
    text: "Dalej",
  },
  {
    id: 25,
    next: 25,
    dialogId: 24,
    text: "Dalej",
  },
  {
    id: 26,
    next: 27,
    dialogId: 25,
    text: "To jest... właściwie mówiąc... pewności nie mam żadnej",
  },
  {
    id: 27,
    next: 26,
    dialogId: 25,
    text: "Jestem pewny, widziałem na własne oczy!",
  },
  {
    id: 28,
    next: 1003,
    dialogId: 26,
    text: "Dalej",
  },
  {
    id: 29,
    next: 28,
    dialogId: 27,
    text: "Dalej",
  },
  {
    id: 30,
    next: 29,
    dialogId: 28,
    text: "Dalej",
  },
  {
    id: 31,
    next: 30,
    dialogId: 29,
    text: "Dalej",
  },
  {
    id: 32,
    next: 31,
    dialogId: 30,
    text: "Dalej",
  },
  {
    id: 33,
    next: 32,
    dialogId: 31,
    text: "Dalej",
  },
  {
    id: 34,
    next: 1001,
    dialogId: 32,
    text: "Tak...",
  },
  {
    id: 35,
    next: 33,
    dialogId: 32,
    text: "Nie wiem która... - szepnęła zapytana.",
  },
  {
    id: 36,
    next: 34,
    dialogId: 33,
    text: "Dalej",
  },
  {
    id: 37,
    next: 35,
    dialogId: 34,
    text: "Dalej",
  },
  {
    id: 38,
    next: 35,
    dialogId: 34,
    text: "Dalej",
  },
  {
    id: 39,
    next: 36,
    dialogId: 35,
    text: "Dalej",
  },
  {
    id: 40,
    next: 37,
    dialogId: 36,
    text: "Dalej",
  },
  {
    id: 41,
    next: 38,
    dialogId: 37,
    text: "Dalej",
  },
  {
    id: 42,
    next: 41,
    dialogId: 39,
    text: "popielatą sukienkę i czarne buciki, a ta ma brązowe buciki!...",
  },
  {
    id: 43,
    next: 40,
    dialogId: 39,
    text: "czerwoną sukienkę i czarne buciki, a ta ma brązowe buciki!...",
  },
  {
    id: 44,
    next: 1005,
    dialogId: 40,
    text: "Dalej",
  },
  {
    id: 45,
    next: 42,
    dialogId: 41,
    text: "Dalej",
  },
  {
    id: 46,
    next: 43,
    dialogId: 42,
    text: "Dalej",
  },
  {
    id: 47,
    next: 44,
    dialogId: 43,
    text: "Dalej",
  },
  {
    id: 48,
    next: 45,
    dialogId: 44,
    text: "Piętnaście rubli.",
  },
  {
    id: 49,
    next: 46,
    dialogId: 44,
    text: "Trzy ruble.",
  },
  {
    id: 50,
    next: 1006,
    dialogId: 45,
    text: "Dalej",
  },
];

export const characters: Character[] = [
  {
    id: 1,
    name: "Stanisław Wokulski",
    image: Wokulski,
  },
  {
    id: 2,
    name: "Ignacy Rzecki",
    image: Rzecki,
  },
  {
    id: 3,
    name: "Adwokat",
    image: Adwokat,
  },
  {
    id: 4,
    name: "Baronowa Krzeszowska",
    image: Baronowa,
  },
  {
    id: 5,
    name: "Dziecko",
    image: Dziecko,
  },
  {
    id: 6,
    name: "Maruszewicz",
    image: Maruszewicz,
  },
  {
    id: 7,
    name: "Sędzia",
    image: Sędzia,
  },
  {
    id: 8,
    name: "Służąca",
    image: Służąca,
  },
  {
    id: 9,
    name: "Helena Stawska",
    image: Stawska,
  },
  {
    id: 10,
    name: "Kobieta 1",
    image: null,
  },
  {
    id: 11,
    name: "Kobieta 2",
    image: null,
  },
  {
    id: 12,
    name: "Mężczyzna 1",
    image: null,
  },
  {
    id: 13,
    name: "Helunia",
    image: null,
  },
  {
    id: 14,
    name: "Wirski",
    image: null,
  },
];

const data: Data = {
  chapters,
  characters,
  choices,
  dialogs,
  metadata,
};

export default data;
