import { Chapter, Dialog, Metadata, Choice, Character, Data } from "./spec";

import win from "../assets/audio/win.mp3";
import loose from "../assets/audio/loose.mp3";

import RozprawaSądowaTło from "../assets/images/rozprawa_sądowa.jpg";
import RozprawaSądowaMuzyka from "../assets/audio/rozprawa_sądowa.mp3";

import Adwokat from "../assets/images/adwokat.png";
import Baronowa from "../assets/images/baronowa.png";
import Dziecko from "../assets/images/dziecko.png";
import Maruszewicz from "../assets/images/maruszewicz.png";
import Rzecki from "../assets/images/rzecki.png";
import Sędzia from "../assets/images/sędzia.png";
import Służąca from "../assets/images/służąca.png";
import Stawska from "../assets/images/stawska.png";
import Wokulski from "../assets/images/wokulski.png";

export const metadata: Metadata = {
  win,
  loose,
};

export const chapters: Chapter[] = [
  {
    id: 1,
    name: "Rozprawa Sądowa",
    slug: "rozprawa-sadowa",
    audio: RozprawaSądowaMuzyka,
    background: RozprawaSądowaTło,
  },
];

export const dialogs: Dialog[] = [
  {
    id: 1,
    chapterId: 1,
    characterId: 7,
    type: "default",
    text: "Sędzia przez parę minut coś pisał, a skończywszy zawiadomił obecnych, że teraz toczyć się będzie sprawa",
  },
  {
    id: 2,
    chapterId: 1,
    characterId: 7,
    type: "default",
    text: "Sędzia zawezwał obie strony oraz świadków na środek sali.",
  },
  {
    id: 3,
    chapterId: 1,
    characterId: 2,
    text: "Rzecki siada w ławce, przysłuchując się rozmowie dwóch kobiet. Jedna z kumoszek tłumaczyła drugiej...",
    type: "default",
  },
  {
    id: 4,
    chapterId: 1,
    characterId: 10,
    text: "To widzi pani: ta ładna pani ukradła tamtej pani lalkę...",
    type: "default",
  },
  {
    id: 5,
    chapterId: 1,
    characterId: 11,
    text: "Także miała się na co łakomić!...",
    type: "default",
  },
  {
    id: 6,
    chapterId: 1,
    characterId: 10,
    text: "Ha, trudno. Nie każdy może kraść magle...",
    type: "default",
  },
  {
    id: 7,
    chapterId: 1,
    characterId: 12,
    text: "To pani ukradłaś magle. Nie ten złodziej, co zabiera swoją własność, ale ten, co da piętnaście rubli zadatku i myśli, że już kupił...",
    type: "default",
  },
  {
    id: 8,
    chapterId: 1,
    characterId: 13,
    text: "Helunia wbiega na salę i chwyta matkę za rękę",
    type: "default",
  },
  {
    id: 9,
    chapterId: 1,
    characterId: 13,
    text: "Mamo, czego ten pan kazał mamie tu przyjść?... Ja coś powiem do uszka: pewnie mama była niegrzeczna i teraz będzie stać w kącie...",
    type: "default",
  },
  {
    id: 10,
    chapterId: 1,
    characterId: 10,
    text: "To wyuczone!...",
    type: "default",
  },
  {
    id: 11,
    chapterId: 1,
    characterId: 12,
    text: "Żebyś pani tak zdrowa była!",
    type: "default",
  },
  {
    id: 12,
    chapterId: 1,
    characterId: 10,
    text: "Pan będziesz zdrów za moją krzywdę...",
    type: "default",
  },
  {
    id: 13,
    chapterId: 1,
    characterId: 12,
    text: "A pani skonasz na konwulsje i będą cię w piekle maglować na moich maglach",
    type: "default",
  },
  {
    id: 14,
    chapterId: 1,
    characterId: 7,
    text: "Panie Rzecki! Zaburza pan porządek na sali sądowej! Nie możemy tak rozpocząć procesu. Będę niestety musiał pana stąd wyprosić. Proszę opuścić salę.",
    type: "default",
  },
  {
    id: 15,
    chapterId: 1,
    characterId: 7,
    text: "Cisza na sali! Co pani Krzeszowska mówi o sprawie?",
    type: "default",
  },
  {
    id: 16,
    chapterId: 1,
    characterId: 4,
    text: "Wysłuchaj mnie, panie sędzio! Po zmarłym dziecku została mi, jako najdroższa pamiątka, lalka, która bardzo podobała się tej oto pani i jej córce",
    type: "default",
  },
  {
    id: 17,
    chapterId: 1,
    characterId: 7,
    text: "Oskarżona była u pani?",
    type: "default",
  },
  {
    id: 18,
    chapterId: 1,
    characterId: 4,
    text: "Tak, wynajmowałam ją do szycia...",
    type: "default",
  },
  {
    id: 19,
    chapterId: 1,
    characterId: 14,
    text: "Alem jej nic nie zapłaciła!",
    type: "default",
  },
  {
    id: 20,
    chapterId: 1,
    characterId: 7,
    text: "Ciszej! Proszę kontynuować",
    type: "default",
  },
  {
    id: 21,
    chapterId: 1,
    characterId: 4,
    text: "W dniu, w którym tę panią oddaliłam od siebie, zginęła mi lalka. Myślałam, że umrę z żalu, i zaraz na nią powzięłam podejrzenie...",
    type: "default",
  },
  {
    id: 22,
    chapterId: 1,
    characterId: 4,
    text: "Miałam dobre przeczucie, gdyż w kilka dni później przyjaciel mój, pan Maruszewicz, zobaczył z okna, że ta pani (która mieszka vis a vis niego) ma u siebie moją lalkę i dla niepoznaki przebiera ją w inną suknię.",
    type: "default",
  },
  {
    id: 23,
    chapterId: 1,
    characterId: 4,
    text: "Wtedy poszłam do jego mieszkania z moim doradcą prawnym i zobaczyłam przez lornetkę, że moja lalka jest rzeczywiście u tej pani. Na drugi dzień więc udałam się do niej, zabrałam lalkę, którą tu widzę na stole, i podałam skargę.",
    type: "default",
  },
  {
    id: 24,
    chapterId: 1,
    characterId: 7,
    text: "A pan Maruszewicz jest pewny, że to ta sama lalka, która była u pani Krzeszowskiej?",
    type: "default",
  },
  {
    id: 25,
    chapterId: 1,
    characterId: 6,
    text: "Marusiewicz wstał i powiedział:",
    type: "default",
  },
  {
    id: 26,
    chapterId: 1,
    characterId: 7,
    text: "Zatem świadków jest dużo. Jeśli lalka rzeczywiście wygląda podobnie - w co jestem skłonny uwierzyć - to muszę przyznać winę pannie Helenie Stawskiej.",
    type: "default",
  },
  {
    id: 27,
    chapterId: 1,
    characterId: 7,
    text: "Tak dlaczegóż pan Maruszewicz powiedział to pani Krzeszowskiej?",
    type: "default",
  },
  {
    id: 28,
    chapterId: 1,
    characterId: 6,
    text: "Właściwie... ja nie w tym znaczeniu...",
    type: "default",
  },
  {
    id: 29,
    chapterId: 1,
    characterId: 4,
    text: "Nie kłam pan! Przybiegłeś do mnie, śmiejąc się, powiedziałeś, że Stawka ukradła lalkę i że to do niej podobne...",
    type: "default",
  },
  {
    id: 30,
    chapterId: 1,
    characterId: 1,
    text: "Podlec!",
    type: "default",
  },
  {
    id: 31,
    chapterId: 1,
    characterId: 7,
    text: "U was była ta lalka?",
    type: "default",
  },
  {
    id: 32,
    chapterId: 1,
    characterId: 9,
    text: "Stawska nieśmiało powiedziała:",
    type: "default",
  },
  {
    id: 33,
    chapterId: 1,
    characterId: 7,
    text: "Sędzia wyciągnął do niej lalkę, ale służąca milczała mrugając oczyma i załamując ręce.",
    type: "default",
  },
  {
    id: 34,
    chapterId: 1,
    characterId: 13,
    text: "Ach, to Mimi!...",
    type: "default",
  },
  {
    id: 35,
    chapterId: 1,
    characterId: 4,
    text: "O, panie sędzio! Córka świadczy przeciw matce...",
    type: "default",
  },
  {
    id: 36,
    chapterId: 1,
    characterId: 7,
    text: "Znasz tę lalkę?",
    type: "default",
  },
  {
    id: 37,
    chapterId: 1,
    characterId: 13,
    text: "O, znam!... Zupełnie taka sama była u pani tam w pokoiku...",
    type: "default",
  },
  {
    id: 38,
    chapterId: 1,
    characterId: 7,
    text: "Czy to jest ta sama?",
    type: "default",
  },
  {
    id: 39,
    chapterId: 1,
    characterId: 13,
    text: "O, nie, nie ta... Tamta miała...",
    type: "default",
  },
  {
    id: 40,
    chapterId: 1,
    characterId: 4,
    text: "Kłamstwo! Moja lalka nie miała czerwonej sukienki. Panie sędzio, czy skoro kłamią w takich drobnostkach, czy można im ufać w ogóle?",
    type: "default",
  },
  {
    id: 41,
    chapterId: 1,
    characterId: 7,
    text: "Co pani Stawska powie?...",
    type: "default",
  },
  {
    id: 42,
    chapterId: 1,
    characterId: 9,
    text: "Lalkę tę kupiłam w sklepie pana Wokulskiego...",
    type: "default",
  },
  {
    id: 43,
    chapterId: 1,
    characterId: 4,
    text: "A ile pani dała za nią?...",
    type: "default",
  },
  {
    id: 44,
    chapterId: 1,
    characterId: 9,
    text: "Stawska odpowiedziała:",
    type: "default",
  },
  {
    id: 45,
    chapterId: 1,
    characterId: 4,
    text: "Tyle, co zapłaciłam ja! Czy to nie jest jednoznacznym dowodem na to, że to jest ta sama lalka, która została u mnie przez nią skradziona?",
    type: "default",
  },
  {
    id: 46,
    chapterId: 1,
    characterId: 4,
    text: "Cha! Cha! Cha!... Ta lalka kosztuje piętnaście...",
    type: "default",
  },
  {
    id: 47,
    chapterId: 1,
    characterId: 7,
    text: "Kto pani sprzedał tę lalkę?",
    type: "default",
  },
  {
    id: 48,
    chapterId: 1,
    characterId: 9,
    text: "Stawska odpowiedziała:",
    type: "default",
  },
  {
    id: 49,
    chapterId: 1,
    characterId: 7,
    text: "Nie jest to możliwe. Słyszałem, iż pan Mraczewski już dawno nie pracuje w sklepie J. Mincel i S. Wokulski. Szanowna Pani skłamała.",
    type: "default",
  },
  {
    id: 50,
    chapterId: 1,
    characterId: 7,
    text: "Co powie pan Rzecki?...",
    type: "default",
  },
  {
    id: 51,
    chapterId: 1,
    characterId: 2,
    text: "Szanowny sędzio!... Z bolesnym zdumieniem przychodzi mi... To jest... widzę przed sobą triumfującą złość i tego... uciśnioną...",
    type: "default",
  },
  {
    id: 52,
    chapterId: 1,
    characterId: 1,
    text: "Wokulski postanowił:",
    type: "default",
  },
  {
    id: 53,
    chapterId: 1,
    characterId: 1,
    text: "Rzecki był tylko obecny przy kupnie, lalkę ja sprzedałem.",
    type: "default",
  },
  {
    id: 54,
    chapterId: 1,
    characterId: 4,
    text: "Za trzy ruble?",
    type: "default",
  },
  {
    id: 55,
    chapterId: 1,
    characterId: 1,
    text: "Tak, za trzy ruble. Jest to towar wybrakowany, którego się pozbywamy.",
    type: "default",
  },
  {
    id: 56,
    chapterId: 1,
    characterId: 4,
    text: "Czy i mnie pan sprzedałby taką lalkę za trzy ruble?",
    type: "default",
  },
  {
    id: 57,
    chapterId: 1,
    characterId: 1,
    text: "Nie! Pani już nic i nigdy nie sprzedadzą w moim sklepie.",
    type: "default",
  },
  {
    id: 58,
    chapterId: 1,
    characterId: 7,
    text: "Jaki pan ma dowód, że ta lalka jest kupiona u pana?",
    type: "default",
  },
  {
    id: 59,
    chapterId: 1,
    characterId: 4,
    text: "Otóż to! Jaki dowód?...",
    type: "default",
  },
  {
    id: 60,
    chapterId: 1,
    characterId: 7,
    text: "Ciszej!...",
    type: "default",
  },
  {
    id: 61,
    chapterId: 1,
    characterId: 1,
    text: "Gdzie pani swoją lalkę kupiła?",
    type: "default",
  },
  {
    id: 62,
    chapterId: 1,
    characterId: 4,
    text: "Baronowa powiedziała:",
    type: "default",
  },
  {
    id: 63,
    chapterId: 1,
    characterId: 1,
    text: "Więc mamy dowód. Lalki takie sprowadzałem z zagranicy w kawałkach: oddzielnie głowy, oddzielnie korpusy.",
    type: "default",
  },
  {
    id: 64,
    chapterId: 1,
    characterId: 1,
    text: "Po czym postanowił:",
    type: "default",
  },
  {
    id: 65,
    chapterId: 1,
    characterId: 1,
    text: "Panie sędzio, nikt inny w całej Warszawie tak nie robi. Wszyscy sprzedają zrobione od razu w całości lalki, ale kosztem większej ceny.",
    type: "default",
  },
  {
    id: 66,
    chapterId: 1,
    characterId: 7,
    text: "Nie jestem przekonany, panie Wokulski. Nie mamy dowodu, że ta lalka rzeczywiście jest zrobiona z osobnych kawałków. Nie mogę panu uwierzyć na słowo.",
    type: "default",
  },
  {
    id: 67,
    chapterId: 1,
    characterId: 1,
    text: "Niech więc pan sędzia odpruje głowę, a wewnątrz znajdzie moją firmę.",
    type: "default",
  },
  {
    id: 68,
    chapterId: 1,
    characterId: 7,
    text: "Sędzia wziął do rąk lalkę, która tyle narobiła zgryzoty, i urzędowym scyzorykiem rozciął jej naprzód stanik, a następnie począł z wielką uwagą odpruwać głowę od tułowia.",
    type: "default",
  },
  {
    id: 69,
    chapterId: 1,
    characterId: 5,
    text: "Mamo, dlaczego ten pan rozbiera Mimi? Przecież ona będzie się wstydzić...",
    type: "default",
  },
  {
    id: 70,
    chapterId: 1,
    characterId: 5,
    text: "Nagle zrozumiawszy, o co chodzi, wybuchnęła płaczem i kryjąc twarz w suknię pani Stawskiej, zawołała:",
    type: "default",
  },
  {
    id: 71,
    chapterId: 1,
    characterId: 5,
    text: "Ach, mamo, po co on ją kraje?... To strasznie boli... O mamo, mamo, już nie chcę, ażeby Mimi krajali...",
    type: "default",
  },
  {
    id: 72,
    chapterId: 1,
    characterId: 1,
    text: "Nie płacz, Heluniu. Mimi będzie zdrowa i jeszcze ładniejsza...",
    type: "default",
  },
  {
    id: 73,
    chapterId: 1,
    characterId: 7,
    text: "Nu, niech pani przeczyta, co tam napisano?",
    type: "default",
  },
  {
    id: 74,
    chapterId: 1,
    characterId: 4,
    text: "...",
    type: "default",
  },
  {
    id: 75,
    chapterId: 1,
    characterId: 7,
    text: "To niech pan Maruszewicz przeczyta głośno, co tam jest.",
    type: "default",
  },
  {
    id: 76,
    chapterId: 1,
    characterId: 6,
    text: "Jan Mincel i Stanisław Wokulski.",
    type: "default",
  },
  {
    id: 77,
    chapterId: 1,
    characterId: 7,
    text: "Zatem nie Lesser?",
    type: "default",
  },
  {
    id: 78,
    chapterId: 1,
    characterId: 6,
    text: "Nie.",
    type: "default",
  },
  {
    id: 79,
    chapterId: 1,
    characterId: 7,
    text: "Teraz panna nam powie, co to było z lalką? Tylko proszę prawdę, bo panna stanie do przysięgi...",
    type: "default",
  },
  {
    id: 80,
    chapterId: 1,
    characterId: 8,
    text: "Lalka stłukła się, panie...",
    type: "default",
  },
  {
    id: 81,
    chapterId: 1,
    characterId: 7,
    text: "Ta wasza lalka, od pani Krzeszowskiej?...",
    type: "default",
  },
  {
    id: 82,
    chapterId: 1,
    characterId: 8,
    text: "Ta...",
    type: "default",
  },
  {
    id: 83,
    chapterId: 1,
    characterId: 7,
    text: "Nu, to stłukła się jej tylko głowa, a reszta gdzie?...",
    type: "default",
  },
  {
    id: 84,
    chapterId: 1,
    characterId: 8,
    text: "Na strychu, panie... Oj, co ja będę miała!",
    type: "default",
  },
  {
    id: 85,
    chapterId: 1,
    characterId: 7,
    text: "Nic panna nie będzie miała; gorzej byłoby nie odpowiedzieć prawdy. A pani oskarżycielka słyszy, co jest?...",
    type: "default",
  },
  {
    id: 86,
    chapterId: 1,
    characterId: 4,
    text: "...",
    type: "default",
  },
  {
    id: 87,
    chapterId: 1,
    characterId: 7,
    text: "Sędzia zaczął pisać.",
    type: "default",
  },
  {
    id: 88,
    chapterId: 1,
    characterId: 12,
    text: "Siedzący w drugiej ławce mężczyzna odezwał się do damy czerwonej na twarzy:",
    type: "default",
  },
  {
    id: 89,
    chapterId: 1,
    characterId: 12,
    text: "A co, ukradła?... Widzisz pani, co się teraz zrobiło z paninej gęby?... Hę?...",
    type: "default",
  },
  {
    id: 90,
    chapterId: 1,
    characterId: 10,
    text: "Jak kobieta jest ładna, to się i z kryminału wygrzebie.",
    type: "default",
  },
  {
    id: 91,
    chapterId: 1,
    characterId: 12,
    text: "Ale pani się nie wygrzebiesz...",
    type: "default",
  },
  {
    id: 92,
    chapterId: 1,
    characterId: 10,
    text: "Głupiś pan!...",
    type: "default",
  },
  {
    id: 93,
    chapterId: 1,
    characterId: 12,
    text: "Paniś głupsza...",
    type: "default",
  },
  {
    id: 94,
    chapterId: 1,
    characterId: 7,
    text: "Ciszej!...",
    type: "default",
  },
  {
    id: 95,
    chapterId: 1,
    characterId: 7,
    text: "Teraz może pani podać skargę o potwarz.",
    type: "default",
  },
  {
    id: 96,
    chapterId: 1,
    characterId: 7,
    text: "Bardzo mi przykro, żem panią sądził, i bardzo mi przyjemnie, że mogę powinszować.",
    type: "default",
  },
  {
    id: 1000,
    chapterId: 1,
    characterId: null,
    text: "Brawo Graczu! Wykazałeś się znajomością lektury. Dzięki Tobie uniewinniono Helenę Stawską. Składamy szczere gratulacje od całej ekipy twórców",
    type: "success",
  },
  {
    id: 1001,
    chapterId: 1,
    characterId: null,
    text: "Mam wrażenie, że nie przeczytałeś lektury. Spróbuj ponownie",
    type: "failure",
  },
  {
    id: 1002,
    chapterId: 1,
    characterId: null,
    text: "Ignacy Rzecki został wyproszony z sali rozpraw przez kłótnię, doprowadzając do przegranej Stawskiej. Spróbuj ponownie",
    type: "failure",
  },
  {
    id: 1003,
    chapterId: 1,
    characterId: null,
    text: "Sędzia uwierzył w kłamstwo Maruszewicza, co doprowadza do przegrane Heleny Stawskiej. Spróbuj ponownie",
    type: "failure",
  },
  {
    id: 1004,
    chapterId: 1,
    characterId: null,
    text: "Pani Stawska nie mogła wytrzymać stresu, który w niej powodowała rozprawa. Liczyła, że dzięki pomocy Ignacego Rzeckiego i Stanisława Wokulskiego uda jej się dojść do wystarczająco pokojowego rozwiązania konfliktu. Niestety baronowa Krzeszowska dobijała się o największą możliwą karę dla Heleny. Niewiele pomogły słowa Rzeckiego i Wokulskiego, kiedy sama przyznała się do rzekomej winy. Stawska przegrała proces",
    type: "failure",
  },
  {
    id: 1005,
    chapterId: 1,
    characterId: null,
    text: "Słowa strony Stawskiej były odbierane z o wiele mniejszym zaufaniem. Ostatecznie baronowej Krzeszowskiej udało się przekonać sędzię o swojej racji. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1006,
    chapterId: 1,
    characterId: null,
    text: "Baronowa Krzeszowska przeciągnęła sędzie na swoją stronę. Skłamała później, że lalkę kupiła w sklepie Stanisława Wokulskiego. Postanowiono, iż baronowa mogła kupić Lalkę w momencie, kiedy w pobliżu nie było ani Rzeckiego, ani Wokulskiego, a więc ich zaprzeczenia słów Krzeszowskiej zostały odebrane jako kłamstwa w celu wybielenia Stawskiej. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1007,
    chapterId: 1,
    characterId: null,
    text: "Pani Stawska została uznana za kłamczynię. Baronowa Krzeszowska więc bez dużego wysiłku przekonała sędzię i ławę przysiężnych, iż jej wersja jest prawdziwa. Nikt nie zwątpił nawet w jej kłamstwo - że rzekomo kupiła lalkę u Wokulskiego. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1008,
    chapterId: 1,
    characterId: null,
    text: "Ignacy Rzecki zaczął się gubić w myślach, więc nie mógł zaoferować pożytecznej pomocy dla Heleny Stawskiej. Sama Pani Stawska nie dała rady obronić.",
    type: "failure",
  },
  {
    id: 1009,
    chapterId: 1,
    characterId: null,
    text: "Kłamstwo baronowej Krzeszowskiej wydało się wiarygodnym zarówno sędziemu, jak i ławie przysiężnych. Dodatkowo zostało potwierdzone przez jej służącą. Zaprzeczenia Stanisława Wokulskiego zostały potraktowane jako kłamstwo w celu wybielenia Heleny Stawskiej. Ostatecznie Krzeszowska zwyciężyła. Stawska przegrała proces.",
    type: "failure",
  },
  {
    id: 1010,
    chapterId: 1,
    characterId: null,
    text: "Stanisław Wokulski postanowił nie robić przykrości Heluni niszcząc jej zabawkę na jej oczach. Niestety przez to sędzia nie mógł zobaczyć napisu w środku lalki, który posłużyłby jednoznacznym dowodem. Nie udało się znaleźć wystarczająco dobrych argumentów i baronowej Krzeszowskiej udało się przekonać sędzię, iż ma rację. Stawska przegrała proces.",
    type: "failure",
  },
];

export const choices: Choice[] = [
  {
    id: 1,
    next: 2,
    dialogId: 1,
    text: "Krzeszowskiej przeciw Stawskiej o kradzież lalki",
  },
  {
    id: 2,
    next: 1001,
    dialogId: 1,
    text: "Wokulski przeciw Stawskiej o kradzież lalki",
  },
  {
    id: 3,
    next: 3,
    dialogId: 2,
    text: "Dalej",
  },
  {
    id: 4,
    next: 4,
    dialogId: 3,
    text: "Dalej",
  },
  {
    id: 5,
    next: 5,
    dialogId: 4,
    text: "Dalej",
  },
  {
    id: 6,
    next: 6,
    dialogId: 5,
    text: "Dalej",
  },
  {
    id: 7,
    next: 7,
    dialogId: 6,
    text: "Dalej",
  },
  {
    id: 8,
    next: 8,
    dialogId: 7,
    text: "Dalej",
  },
  {
    id: 9,
    next: 9,
    dialogId: 8,
    text: "Dalej",
  },
  {
    id: 10,
    next: 10,
    dialogId: 9,
    text: "Dalej",
  },
  {
    id: 11,
    next: 11,
    dialogId: 10,
    text: "Dalej",
  },
  {
    id: 12,
    next: 12,
    dialogId: 11,
    text: "Dalej",
  },
  {
    id: 13,
    next: 13,
    dialogId: 12,
    text: "Dalej",
  },
  {
    id: 14,
    next: 15,
    dialogId: 13,
    text: "Sędzia ucisza tłum",
  },
  {
    id: 15,
    next: 14,
    dialogId: 13,
    text: "Rzecki wtrąca się do kłótni stając w obronie Stawskiej",
  },
  {
    id: 16,
    next: 1002,
    dialogId: 14,
    text: "Dalej",
  },
  {
    id: 17,
    next: 16,
    dialogId: 15,
    text: "Dalej",
  },
  {
    id: 18,
    next: 17,
    dialogId: 16,
    text: "Dalej",
  },
  {
    id: 19,
    next: 18,
    dialogId: 17,
    text: "Dalej",
  },
  {
    id: 20,
    next: 19,
    dialogId: 18,
    text: "Dalej",
  },
  {
    id: 21,
    next: 20,
    dialogId: 19,
    text: "Dalej",
  },
  {
    id: 22,
    next: 21,
    dialogId: 20,
    text: "Dalej",
  },
  {
    id: 23,
    next: 22,
    dialogId: 21,
    text: "Dalej",
  },
  {
    id: 24,
    next: 23,
    dialogId: 22,
    text: "Dalej",
  },
  {
    id: 25,
    next: 24,
    dialogId: 23,
    text: "Dalej",
  },
  {
    id: 26,
    next: 25,
    dialogId: 24,
    text: "Dalej",
  },
  {
    id: 27,
    next: 27,
    dialogId: 25,
    text: "To jest... właściwie mówiąc... pewności nie mam żadnej",
  },
  {
    id: 28,
    next: 26,
    dialogId: 25,
    text: "Jestem pewny, widziałem na własne oczy!",
  },
  {
    id: 29,
    next: 1003,
    dialogId: 26,
    text: "Dalej",
  },
  {
    id: 30,
    next: 28,
    dialogId: 27,
    text: "Dalej",
  },
  {
    id: 31,
    next: 29,
    dialogId: 28,
    text: "Dalej",
  },
  {
    id: 32,
    next: 30,
    dialogId: 29,
    text: "Dalej",
  },
  {
    id: 33,
    next: 31,
    dialogId: 30,
    text: "Dalej",
  },
  {
    id: 34,
    next: 32,
    dialogId: 31,
    text: "Dalej",
  },
  {
    id: 35,
    next: 1001,
    dialogId: 32,
    text: "Tak...",
  },
  {
    id: 36,
    next: 33,
    dialogId: 32,
    text: "Nie wiem która... - szepnęła zapytana.",
  },
  {
    id: 37,
    next: 34,
    dialogId: 33,
    text: "Dalej",
  },
  {
    id: 38,
    next: 35,
    dialogId: 34,
    text: "Dalej",
  },
  {
    id: 39,
    next: 36,
    dialogId: 35,
    text: "Dalej",
  },
  {
    id: 40,
    next: 37,
    dialogId: 36,
    text: "Dalej",
  },
  {
    id: 41,
    next: 38,
    dialogId: 37,
    text: "Dalej",
  },
  {
    id: 200,
    next: 39,
    dialogId: 38,
    text: "Dalej",
  },
  {
    id: 42,
    next: 41,
    dialogId: 39,
    text: "...popielatą sukienkę i czarne buciki, a ta ma brązowe buciki!...",
  },
  {
    id: 43,
    next: 40,
    dialogId: 39,
    text: "...czerwoną sukienkę i czarne buciki, a ta ma brązowe buciki!...",
  },
  {
    id: 44,
    next: 1005,
    dialogId: 40,
    text: "Dalej",
  },
  {
    id: 45,
    next: 42,
    dialogId: 41,
    text: "Dalej",
  },
  {
    id: 46,
    next: 43,
    dialogId: 42,
    text: "Dalej",
  },
  {
    id: 47,
    next: 44,
    dialogId: 43,
    text: "Dalej",
  },
  {
    id: 48,
    next: 45,
    dialogId: 44,
    text: "Piętnaście rubli.",
  },
  {
    id: 49,
    next: 46,
    dialogId: 44,
    text: "Trzy ruble.",
  },
  {
    id: 50,
    next: 1006,
    dialogId: 45,
    text: "Dalej",
  },
  {
    id: 51,
    next: 47,
    dialogId: 46,
    text: "Dalej",
  },
  {
    id: 52,
    next: 48,
    dialogId: 47,
    text: "Dalej",
  },
  {
    id: 53,
    next: 49,
    dialogId: 48,
    text: "Pan Mraczewski.",
  },
  {
    id: 54,
    next: 50,
    dialogId: 48,
    text: "Pan Rzecki.",
  },
  {
    id: 55,
    next: 1007,
    dialogId: 49,
    text: "Dalej",
  },
  {
    id: 56,
    next: 51,
    dialogId: 50,
    text: "Dalej",
  },
  {
    id: 57,
    next: 52,
    dialogId: 51,
    text: "Dalej",
  },
  {
    id: 58,
    next: 1008,
    dialogId: 52,
    text: "Nie wtrącać się.",
  },
  {
    id: 59,
    next: 53,
    dialogId: 52,
    text: "Wtrącić się.",
  },
  {
    id: 60,
    next: 54,
    dialogId: 53,
    text: "Dalej",
  },
  {
    id: 61,
    next: 55,
    dialogId: 54,
    text: "Dalej",
  },
  {
    id: 62,
    next: 56,
    dialogId: 55,
    text: "Dalej",
  },
  {
    id: 63,
    next: 57,
    dialogId: 56,
    text: "Dalej",
  },
  {
    id: 64,
    next: 58,
    dialogId: 57,
    text: "Dalej",
  },
  {
    id: 65,
    next: 59,
    dialogId: 58,
    text: "Dalej",
  },
  {
    id: 66,
    next: 60,
    dialogId: 59,
    text: "Dalej",
  },
  {
    id: 67,
    next: 61,
    dialogId: 60,
    text: "Dalej",
  },
  {
    id: 68,
    next: 62,
    dialogId: 61,
    text: "Dalej",
  },
  {
    id: 69,
    next: 1009,
    dialogId: 62,
    text: "U pana Wokulskiego",
  },
  {
    id: 70,
    next: 63,
    dialogId: 62,
    text: "U Lessera",
  },
  {
    id: 71,
    next: 64,
    dialogId: 63,
    text: "Dalej",
  },
  {
    id: 72,
    next: 67,
    dialogId: 64,
    text: "Odpruć lalkę",
  },
  {
    id: 73,
    next: 65,
    dialogId: 64,
    text: "Powiedzieć, że takie lalki sprzedaje tylko on",
  },
  {
    id: 74,
    next: 66,
    dialogId: 65,
    text: "Dalej",
  },
  {
    id: 75,
    next: 1010,
    dialogId: 66,
    text: "Dalej",
  },
  {
    id: 76,
    next: 68,
    dialogId: 67,
    text: "Dalej",
  },
  {
    id: 77,
    next: 69,
    dialogId: 68,
    text: "Dalej",
  },
  {
    id: 78,
    next: 70,
    dialogId: 69,
    text: "Dalej",
  },
  {
    id: 79,
    next: 71,
    dialogId: 70,
    text: "Dalej",
  },
  {
    id: 80,
    next: 72,
    dialogId: 71,
    text: "Dalej",
  },
  {
    id: 81,
    next: 73,
    dialogId: 72,
    text: "Dalej",
  },
  {
    id: 82,
    next: 74,
    dialogId: 73,
    text: "Dalej",
  },
  {
    id: 83,
    next: 75,
    dialogId: 74,
    text: "Dalej",
  },
  {
    id: 84,
    next: 76,
    dialogId: 75,
    text: "Dalej",
  },
  {
    id: 85,
    next: 77,
    dialogId: 76,
    text: "Dalej",
  },
  {
    id: 86,
    next: 78,
    dialogId: 77,
    text: "Dalej",
  },
  {
    id: 87,
    next: 79,
    dialogId: 78,
    text: "Dalej",
  },
  {
    id: 88,
    next: 80,
    dialogId: 79,
    text: "Dalej",
  },
  {
    id: 89,
    next: 81,
    dialogId: 80,
    text: "Dalej",
  },
  {
    id: 90,
    next: 82,
    dialogId: 81,
    text: "Dalej",
  },
  {
    id: 91,
    next: 83,
    dialogId: 82,
    text: "Dalej",
  },
  {
    id: 92,
    next: 84,
    dialogId: 83,
    text: "Dalej",
  },
  {
    id: 93,
    next: 85,
    dialogId: 84,
    text: "Dalej",
  },
  {
    id: 94,
    next: 86,
    dialogId: 85,
    text: "Dalej",
  },
  {
    id: 95,
    next: 87,
    dialogId: 86,
    text: "Dalej",
  },
  {
    id: 96,
    next: 88,
    dialogId: 87,
    text: "Dalej",
  },
  {
    id: 97,
    next: 89,
    dialogId: 88,
    text: "Dalej",
  },
  {
    id: 98,
    next: 90,
    dialogId: 89,
    text: "Dalej",
  },
  {
    id: 99,
    next: 91,
    dialogId: 90,
    text: "Dalej",
  },
  {
    id: 100,
    next: 92,
    dialogId: 91,
    text: "Dalej",
  },
  {
    id: 101,
    next: 93,
    dialogId: 92,
    text: "Dalej",
  },
  {
    id: 300,
    next: 94,
    dialogId: 93,
    text: "Dalej",
  },
  {
    id: 102,
    next: 95,
    dialogId: 94,
    text: "Dalej",
  },
  {
    id: 103,
    next: 96,
    dialogId: 95,
    text: "Dalej",
  },
  {
    id: 104,
    next: 1000,
    dialogId: 96,
    text: "Dalej",
  },
];

export const characters: Character[] = [
  {
    id: 1,
    name: "Stanisław Wokulski",
    image: Wokulski,
  },
  {
    id: 2,
    name: "Ignacy Rzecki",
    image: Rzecki,
  },
  {
    id: 3,
    name: "Adwokat",
    image: Adwokat,
  },
  {
    id: 4,
    name: "Baronowa Krzeszowska",
    image: Baronowa,
  },
  {
    id: 5,
    name: "Helunia",
    image: Dziecko,
  },
  {
    id: 6,
    name: "Maruszewicz",
    image: Maruszewicz,
  },
  {
    id: 7,
    name: "Sędzia",
    image: Sędzia,
  },
  {
    id: 8,
    name: "Służąca",
    image: Służąca,
  },
  {
    id: 9,
    name: "Helena Stawska",
    image: Stawska,
  },
  {
    id: 10,
    name: "Kobieta 1",
    image: null,
  },
  {
    id: 11,
    name: "Kobieta 2",
    image: null,
  },
  {
    id: 12,
    name: "Mężczyzna 1",
    image: null,
  },
  {
    id: 13,
    name: "Helunia",
    image: Dziecko,
  },
  {
    id: 14,
    name: "Wirski",
    image: null,
  },
];

const data: Data = {
  chapters,
  characters,
  choices,
  dialogs,
  metadata,
};

export default data;
